init -20 python:
    from game.systems import rm_core

    RM_ATTRIBUTES = rm_core.ATTRIBUTES
    RM_ATTRIBUTE_LABELS = rm_core.ATTRIBUTE_LABELS
    RM_ACTION_SCHEDULE = rm_core.ACTION_SCHEDULE
    RM_ACTION_INSTANT = rm_core.ACTION_INSTANT
    RM_ACTION_FORCED_SCHEDULE = rm_core.ACTION_FORCED_SCHEDULE

    RM_ENCHANT_LIGHT = rm_core.ENCHANT_LIGHT
    RM_ENCHANT_SWIFT = rm_core.ENCHANT_SWIFT
    RM_ENCHANT_SEAL = rm_core.ENCHANT_SEAL
    RM_ENCHANT_SHACKLE = rm_core.ENCHANT_SHACKLE
    RM_ENCHANT_HEAVY = rm_core.ENCHANT_HEAVY
    RM_ENCHANT_SLUGGISH = rm_core.ENCHANT_SLUGGISH

