default rm_ui_layouts = {
    "dice_select": {
        "background": {
            "image": "gui/ui_test_skin/dice_check_panel.png",
            "x": 0,
            "y": 0,
            "w": 1920,
            "h": 1080,
            "z": 0,
            "alpha": 0.35,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "clock_face": {
            "image": "gui/ui_test_skin/clock_face.png",
            "x": 55,
            "y": 55,
            "w": 135,
            "h": 135,
            "z": 10,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "clock_hand": {
            "image": "gui/ui_test_skin/clock_hand.png",
            "x": 108,
            "y": 70,
            "w": 32,
            "h": 92,
            "z": 11,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "mood_bar": {
            "image": "gui/story_ui/ui_mood_bar_canvas.png",
            "x": 210,
            "y": 72,
            "w": 470,
            "h": 30,
            "z": 10,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "mood_cursor": {
            "image": "gui/ui_test_skin/mood_cursor.png",
            "x": 420,
            "y": 46,
            "w": 34,
            "h": 82,
            "z": 12,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "energy_bar_green": {
            "image": "gui/story_ui/ui_energy_full_canvas.png",
            "x": 210,
            "y": 115,
            "w": 470,
            "h": 30,
            "z": 10,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "energy_bar_gray": {
            "image": "gui/story_ui/ui_energy_empty_canvas.png",
            "x": 210,
            "y": 115,
            "w": 470,
            "h": 30,
            "z": 9,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "energy_cursor": {
            "image": "gui/ui_test_skin/mood_cursor.png",
            "x": 610,
            "y": 102,
            "w": 34,
            "h": 82,
            "z": 12,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "status_panel_base": {
            "image": "gui/ui_test_skin/dice_list.png",
            "x": 65,
            "y": 300,
            "w": 180,
            "h": 360,
            "z": 5,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "status_note_1": {
            "image": "gui/ui_test_skin/option_button.png",
            "x": 83,
            "y": 375,
            "w": 140,
            "h": 70,
            "z": 6,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "status_note_2": {
            "image": "gui/ui_test_skin/option_button.png",
            "x": 83,
            "y": 470,
            "w": 140,
            "h": 82,
            "z": 6,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "main_clipboard": {
            "image": "gui/ui_test_skin/dice_check_panel.png",
            "x": 310,
            "y": 115,
            "w": 1310,
            "h": 810,
            "z": 1,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "dice_card_blank": {
            "image": "gui/ui_test_skin/dice_card.png",
            "x": 860,
            "y": 398,
            "w": 185,
            "h": 220,
            "z": 15,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "dice_icon_d6": {
            "image": "gui/ui_test_skin/clock_face.png",
            "x": 912,
            "y": 450,
            "w": 82,
            "h": 82,
            "z": 16,
            "alpha": 0.65,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "confirm_button": {
            "image": "gui/ui_test_skin/prominent_tab.png",
            "x": 1350,
            "y": 805,
            "w": 215,
            "h": 100,
            "z": 20,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "detail_popup_blank": {
            "image": "gui/ui_test_skin/dice_list.png",
            "x": 1220,
            "y": 260,
            "w": 360,
            "h": 410,
            "z": 30,
            "alpha": 0.95,
            "rotate": 0,
            "locked": False,
            "visible": False,
        },
    }
}

default rm_ui_layout_initials = {}
