default rm_ui_layouts = {
    "dice_select": {
        "background": {
            "image": "gui/ui_test_skin/dice_check_panel.png",
            "x": 0,
            "y": 0,
            "w": 2560,
            "h": 1440,
            "z": 0,
            "alpha": 0.35,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "clock_face": {
            "image": "gui/ui_test_skin/clock_face.png",
            "x": 73,
            "y": 73,
            "w": 180,
            "h": 180,
            "z": 10,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "clock_hand": {
            "image": "gui/ui_test_skin/clock_hand.png",
            "x": 144,
            "y": 93,
            "w": 43,
            "h": 123,
            "z": 11,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "mood_bar": {
            "image": "gui/story_ui/ui_mood_bar_canvas.png",
            "x": 280,
            "y": 96,
            "w": 627,
            "h": 40,
            "z": 10,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "mood_cursor": {
            "image": "gui/ui_test_skin/mood_cursor.png",
            "x": 560,
            "y": 61,
            "w": 45,
            "h": 109,
            "z": 12,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "energy_bar_green": {
            "image": "gui/story_ui/ui_energy_full_canvas.png",
            "x": 280,
            "y": 153,
            "w": 627,
            "h": 40,
            "z": 10,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "energy_bar_gray": {
            "image": "gui/story_ui/ui_energy_empty_canvas.png",
            "x": 280,
            "y": 153,
            "w": 627,
            "h": 40,
            "z": 9,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "energy_cursor": {
            "image": "gui/ui_test_skin/mood_cursor.png",
            "x": 813,
            "y": 136,
            "w": 45,
            "h": 109,
            "z": 12,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "status_panel_base": {
            "image": "gui/ui_test_skin/dice_list.png",
            "x": 87,
            "y": 400,
            "w": 240,
            "h": 480,
            "z": 5,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "status_note_1": {
            "image": "gui/ui_test_skin/option_button.png",
            "x": 111,
            "y": 500,
            "w": 187,
            "h": 93,
            "z": 6,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "status_note_2": {
            "image": "gui/ui_test_skin/option_button.png",
            "x": 111,
            "y": 627,
            "w": 187,
            "h": 109,
            "z": 6,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "main_clipboard": {
            "image": "gui/ui_test_skin/dice_check_panel.png",
            "x": 413,
            "y": 153,
            "w": 1747,
            "h": 1080,
            "z": 1,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "dice_card_blank": {
            "image": "gui/ui_test_skin/dice_card.png",
            "x": 1147,
            "y": 531,
            "w": 247,
            "h": 293,
            "z": 15,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "dice_icon_d6": {
            "image": "gui/ui_test_skin/clock_face.png",
            "x": 1216,
            "y": 600,
            "w": 109,
            "h": 109,
            "z": 16,
            "alpha": 0.65,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "confirm_button": {
            "image": "gui/ui_test_skin/prominent_tab.png",
            "x": 1800,
            "y": 1073,
            "w": 287,
            "h": 133,
            "z": 20,
            "alpha": 1.0,
            "rotate": 0,
            "locked": False,
            "visible": True,
        },
        "detail_popup_blank": {
            "image": "gui/ui_test_skin/dice_list.png",
            "x": 1627,
            "y": 347,
            "w": 480,
            "h": 547,
            "z": 30,
            "alpha": 0.95,
            "rotate": 0,
            "locked": False,
            "visible": False,
        },
    }
}

default rm_ui_layout_initials = {}
